language: python
python:
    - "3.5"
install:
    - pip install -r requirements.txt
script:
    - bash make.sh
after_success:
    - bash deploy.sh
env:
    global:
        - secure: "HkI0NJy4XDHC/7HMhjkLUW/dJYOi8irePyPHRRu2yQXbx2n7+zGjXFRsfQLjgEtorOyVJMhmW/4wKG62xi/xvoEewF/MN0EmrfK6HjwZiQQEHijpVhrIfPZyUwIes67dAMYdmGDIJFL38M4HRgoB4Hr0QUcahB85NvRIm+/3G8yYNFVcm5NOZ5onbAvZzOb4K2BtxP9fXQAdvSYfQawdETfzT06b8VQfcGps4btT/jhAU9WSAp5IE1FMpgvllObQv4FvSmrFWTNhCSGooTShP8Vsbg1WcwIlNNMBzg9vjQ/J/z0247dtJhkLaw2WkCh8uIAgUDg86tNhWLWi42l6kq84KPyOYyXE29tIDafSwTY/wsaN540FlpHZJhGZ7yr1B2vVFF+dC7xBVKwbH12zdJaUwLzWy2apajePMgB0x/NbESJ8R+rvKytAyuSw8Y97MEgccLyzbnZFK7hsPtNC1wdU1K22Vonh4qkjvd570ahKNIGe35YCyH/P4jxQiTiuC2KthY1VS2dkp86QUF2tEeubApDwOuaJ3W1exAGjf7hCVqqr6Wn7nG5F4+9bR1o7nxDVrZ5SsJ1nfNRrV9M0ZdobJAJH4egg0TqMh2d94uWQvoXx52+rRSIhTLTL4VkOC7OeGlpKjKjd6roRiPDS9uy7oTBJUmRW7iI3X7OjQuk="

